name: flexdocs_flutter
description: "FlexDocs Flutter SDK - Database, Auth, and Storage backend-as-a-service."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
